### ISSUE TITLE
[Android]Can't open.

### ISSUE THREAD

**Issue by sohobloo** [philipphecht/react-native-doc-viewer#3]
Error logs:

03-21 13:34:23.256 7011-7011/com.zangku.zangku I/System.out: Mime Type: application/pdf
03-21 13:34:23.259 7011-7011/com.zangku.zangku W/System.err: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=file:///data/user/0/com.zangku.zangku/cache/zangku_files/2dbe0a09826b4e3c97df1f873717f3c0/ios.pdf typ=application/pdf flg=0x10000000 }
03-21 13:34:23.259 7011-7011/com.zangku.zangku W/System.err:     at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1798)
03-21 13:34:23.259 7011-7011/com.zangku.zangku W/System.err:     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1512)
03-21 13:34:23.259 7011-7011/com.zangku.zangku W/System.err:     at android.app.ContextImpl.startActivity(ContextImpl.java:677)
03-21 13:34:23.259 7011-7011/com.zangku.zangku W/System.err:     at android.app.ContextImpl.startActivity(ContextImpl.java:659)
03-21 13:34:23.259 7011-7011/com.zangku.zangku W/System.err:     at android.content.ContextWrapper.startActivity(ContextWrapper.java:331)
03-21 13:34:23.259 7011-7011/com.zangku.zangku W/System.err:     at com.reactlibrary.RNReactNativeDocViewerModule$FileDownloaderAsyncTask.onPostExecute(RNReactNativeDocViewerModule.java:207)
03-21 13:34:23.259 7011-7011/com.zangku.zangku W/System.err:     at com.reactlibrary.RNReactNativeDocViewerModule$FileDownloaderAsyncTask.onPostExecute(RNReactNativeDocViewerModule.java:164)
03-21 13:34:23.259 7011-7011/com.zangku.zangku W/System.err:     at android.os.AsyncTask.finish(AsyncTask.java:651)
03-21 13:34:23.259 7011-7011/com.zangku.zangku W/System.err:     at android.os.AsyncTask.-wrap1(AsyncTask.java)
03-21 13:34:23.259 7011-7011/com.zangku.zangku W/System.err:     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
03-21 13:34:23.259 7011-7011/com.zangku.zangku W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
03-21 13:34:23.259 7011-7011/com.zangku.zangku W/System.err:     at android.os.Looper.loop(Looper.java:148)
03-21 13:34:23.259 7011-7011/com.zangku.zangku W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
03-21 13:34:23.259 7011-7011/com.zangku.zangku W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-21 13:34:23.259 7011-7011/com.zangku.zangku W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-21 13:34:23.259 7011-7011/com.zangku.zangku W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by philipphecht** [comment]
I think you don't have an application that supports pdf's. i check this.

**Comment by sohobloo** [comment]
Yes, I thought this component had integrated something like iOS' QuickLook.
Will you do this in Android?

**Comment by philipphecht** [comment]
Yes. i think in one week.

**Comment by Tako** [comment]
Android is still in progress ?

**Comment by philipphecht** [comment]
Yes it is still in progress.
